# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Security/Secret-Detection.gitlab-ci.yml


# Переопределяем стандартный шаблон: 
# https://gitlab.com/gitlab-org/security-products/analyzers/secrets/-/tree/master#L559
secret_detection:
  stage: pre-build
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"  # Для проверки более ранних коммитов
    GIT_STRATEGY: "clone"
  # allow_failure: false  # Стоп если не прошли
  allow_failure: true
  script:
    - apk add jq  # тулза для работы с .json
    - /analyzer run
    # бесплатный сканер не останавливается при проверке. Делаем спец выход
    - exit $(eval "cat gl-secret-detection-report.json | jq --raw-output '.vulnerabilities | length'")
