---
# tasks file for nginx

- block:
  - name: install nginx package on RedHat
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx package on debian systems
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: ensure nginx is enebled and running
    service:
      name: nginx
      state: started
      enabled: yes

  - name: disable default site if required
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    when: not nginx_default_sites_enabled

  - name: deploy nginx configuration file
    template:
      src: nginx.conf.j2
      dest: '{{ nginx_conf_path }}'
      owner: root
      group: root
      mode: '0644'
      backup: yes
    notify:
      - reload nginx
  become: true