---
# tasks file for hostname

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"

- name: Check name
  ansible.builtin.shell: cat /etc/hostname
  register: hostname_check

- name: Print hostname_check variable
  ansible.builtin.debug:
    var: hostname_check.stdout_lines
