# roles/swaptrasher/tasks/main.yml
---
# Удаление swap

- block:
  - name: Delete string in fstab by fstype
    mount:
      path: none
      fstype: swap
      state: absent

  - name: Get path to swap
    shell: swapon --show | awk '/swap/ {print $1}'
    register: swap_path
  - debug:
      var: swap_path.stdout

  - name: Disable the swap file
    shell: swapoff {{ swap_path.stdout }}
    when: ansible_facts.swapfree_mb > 0

  - name: Delete the swap file
    file:
      path: swap_path.stdout
      state: absent
  become: yes
